---
# handlers file for acmetool
- name: 'Run acmetool quickstart'
  shell: acmetool quickstart --batch --response-file {{ acmetool_working_directory }}/conf/responses
  become: yes
  become_user: "{{ acmetool_user }}"

- name: 'Run acmetool reconcile'
  shell: acmetool reconcile --batch --response-file {{ acmetool_working_directory }}/conf/responses
  become: yes
  become_user: "{{ acmetool_user }}"
